# Generated by Django 2.2.7 on 2019-11-27 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_userdetails_conver'),
    ]

    operations = [
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conver', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='userdetails',
            name='conver',
        ),
    ]
