# Generated by Django 2.2.7 on 2019-11-27 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_auto_20191127_1739'),
    ]

    operations = [
        migrations.RenameField(
            model_name='text',
            old_name='conver',
            new_name='temp',
        ),
    ]
