# Generated by Django 2.1.1 on 2019-11-20 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('height', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('smoke', models.BooleanField()),
                ('drink', models.BooleanField()),
                ('diabetes', models.BooleanField()),
                ('highbp', models.BooleanField()),
                ('symptoms',models.BooleanField())
            ],
        ),
    ]
