# Generated by Django 2.2.7 on 2019-11-21 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetails',
            name='symptoms',
        ),
        migrations.AddField(
            model_name='userdetails',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default=30, max_length=6),
            preserve_default=False,
        ),
    ]
