# Generated by Django 2.1.1 on 2019-11-25 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20191121_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='conver',
            field=models.CharField(default=600, max_length=255),
            preserve_default=False,
        ),
    ]
